name: Build Python Package (Ubuntu 22.04)
on: push
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        sudo apt-get install -y xorg-dev libwayland-dev libxkbcommon-dev
    - name: Build package
      run: python -m build
